services:
  backend:
    build:
      context: ./backend
    container_name: drr-backend
    ports:
      - "8000:8000"
    volumes:
      - ./Test_Data:/data:ro
    environment:
      - NIFTI_PATH=/data/HN_P001.nii.gz

  frontend:
    build:
      context: ./frontend
    container_name: drr-frontend
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend
